version: "3"
services:
  ec-cube:
    build: ./docker/eccube
    image: eccube:1.0.1
    container_name: eccube-demo
    volumes:
      - .:/var/www/html
      - /path/to/certs:/etc/letsencrypt/live
    environment:
      - HOST_UID
      - VIRTUAL_HOST=demo.ilandwig.com
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-demo.ilandwig.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-zouhideo@gmail.com}
      - XDEBUG_PORT=${XDEBUG_PORT:-9000}
      - APP_ENV=${APP_ENV:-prod}
      - APP_DEBUG=${APP_DEBUG:-1}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-127.0.0.1,127.0.0.2}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:-localhost,ilandwig.com}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///%kernel.project_dir%/var/eccube.db}
      - DATABASE_SERVER_VERSION=${DATABASE_SERVER_VERSION:-3}
      - MAILER_URL=${MAILER_URL:-null://localhost}
      - ECCUBE_LOCALE=${ECCUBE_LOCALE:-ja}
      - ECCUBE_TIMEZONE=${ECCUBE_TIMEZONE:-Asia/Tokyo}
      - ECCUBE_CURRENCY=${ECCUBE_CURRENCY:-JPY}
      - ECCUBE_ADMIN_ROUTE=${ECCUBE_ADMIN_ROUTE:-admz}
      - ECCUBE_USER_DATA_ROUTE=${ECCUBE_USER_DATA_ROUTE:-user_data}
      - ECCUBE_ADMIN_ALLOW_HOSTS=${ECCUBE_ADMIN_ALLOW_HOSTS:-[]}
      - ECCUBE_FORCE_SSL=${ECCUBE_FORCE_SSL:-true}
      - ECCUBE_TEMPLATE_CODE=${ECCUBE_TEMPLATE_CODE:-default}
      - ECCUBE_AUTH_MAGIC=${ECCUBE_AUTH_MAGIC:-supersecureauthmagic}
      - ECCUBE_COOKIE_NAME=${ECCUBE_COOKIE_NAME:-ilandwig}
      - ECCUBE_COOKIE_PATH=${ECCUBE_COOKIE_PATH:-/}
      - ECCUBE_COOKIE_LIFETIME=${ECCUBE_COOKIE_LIFETIME:-0}
      - ECCUBE_GC_MAXLIFETIME=${ECCUBE_GC_MAXLIFETIME:-1440}
    expose:
      - "80"
      - "443"
      - "9000"
